### ISSUE TITLE
0x03강 연습문제 2 코드에 관해

### ISSUE THREAD

**Issue by encrypted-def** [J-Shine/J-Shine.github.io#1]
안녕하세요, 작성해주시는 포스팅 잘 보고 있습니다. 다름이 아니라 연습문제 2의 코드에서 freq[arr[i]-1]++이 있는데 arr의 수는 0 이상 100 이하라는 조건이 있고 그 말은 곧 0도 가능하기 때문에 runtime error가 발생할 수 있습니다.

그래서 freq 배열을 101칸으로 두고 freq[arr[i]]에 접근하도록 작성해야 문제가 없을듯합니다. 그러면 좋은 주말 보내세요!!

**Comment by J-Shine** [comment]
헉 바킹독님이 댓글을 달아주시다니 ㄷㄷ
중요한 문제점 지적해주셔서 감사합니다 ㅎㅎ 앞으로도 문제점 보이면 말해주시면 감사하겠습니다!

**Comment by J-Shine** [comment]
헉 바킹독님이 댓글을 달아주시다니 ㄷㄷ
중요한 문제점 지적해주셔서 감사합니다 ㅎㅎ 앞으로도 문제점 보이면 말해주시면 감사하겠습니다!

**Comment by encrypted-def** [comment]
넵!! J-Shine님도 강의 보다가 개선점 알려주시면 감사히 받겠습니다ㅎㅎ
